# 我使用的是 Leaveit 主题，所以以该主题的配置文件为例
baseURL = ""
languageCode = "zh-CN"
title = ""              # 你的网站名称
theme = "LeaveIt"       # 当前使用的主题名称，与 themes 文件夹中的子文件夹名称一致

paginate = 15           # 每页显示的博文数量
enableEmoji = true      # 允许使用 Emoji 表情，建议 true
enableRobotsTXT = true  # 允许爬虫抓取到搜索引擎，建议 true
googleAnalytics = ""    # 谷歌统计

preserveTaxonomyNames = true
hasCJKLanguage = true    # 正确显示文章字数统计，建议为 true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = ""                   # Author's name
    avatar = "images/avatar.jpeg" # Author's avatar
    subtitle = "Fuck The Life"    # Subtitle
    cdn_url = ""                  # Base CDN URL
    home_mode = ""                # post or other

    google_verification = ""

    description = ""              # site description
    keywords = ""                 # site keywords
    favicon = "favicon.ico"
    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "xxoo"
    Twitter = "xxoo"
    Email   = "xxoo"
    Instagram = "xxoo"
    Wechat = "xxoo"               # Wechat QRcode image
    Facebook = "xxoo"
    Telegram = "xxoo"
    Dribbble = "xxoo"
    Medium = "xxoo"